### ISSUE TITLE
helm-chart action fails on master branch

### ISSUE THREAD

**Issue by celiala** [cockroachdb/helm-charts#310]
https://github.com/cockroachdb/helm-charts/actions?query=branch%3Amaster

Last passing run against `master` was July 2022: https://github.com/cockroachdb/helm-charts/actions/runs/2657195035

**Comment by prafull01** [comment]
This job is intended to pass only when there is some code level changes in `self-signer` utility and when it passes we know that we have to build and push a new version of `self-signer` utility only when the tag is changed.

Self-signer utility is stable from long time and hence that job doesn't passes. However, I will add a fix so that job doesn't fail when tagChange is not true.

**Comment by michae2** [comment]
@prafull01 it looks like this still might be failing? For example: https://github.com/cockroachdb/helm-charts/actions/runs/5262327917

**Comment by rail** [comment]
I filed https://github.com/cockroachdb/helm-charts/pull/320 to follow up the fix.
