### ISSUE TITLE
cockroach-self-signer-cert:1.4 is not multi-arch

### ISSUE THREAD

**Issue by samip5** [cockroachdb/helm-charts#330]
This currently fails to uninstall due to that fact.

**Comment by prafull01** [comment]
@himanshu-cockroach Can you please have a look.

**Comment by mprimeaux** [comment]
+1 for supporting ARM64 as that CPU architecture represents a 40% cost per transaction savings for our workloads. 

For local development in minikube, the workaround I've managed to fine is to follow the manual steps [here](https://github.com/cockroachdb/helm-charts/tree/master/cockroachdb#manual).

Please let me know how I can help.

**Comment by mprimeaux** [comment]
@prafull01 I'm sure everyone is busy but would the maintainers be supportive of me contributing to a multi-arch build process for the cockroach-self-signer?

**Comment by prafull01** [comment]
Hi @mprimeaux Thank you for taking interest in the contributing. We accept every kind of contribution from the community.

I have already been working on the implementing the arm64 build process for self signer and also supporting the arm64 architecture on the openshift. You will see the PR for that by today EOD.

**Comment by mprimeaux** [comment]
Hi @prafull01 - can I help with anything on the PR? Happy to help or test.

**Comment by prafull01** [comment]
Hi @mprimeaux 
I have added the PR for the linux/arm64 support. I have tested it on GKE, please feel free to test it on your own.
![Uploading Screenshot 2023-09-09 at 11.11.05 PM.png…]()

**Comment by mprimeaux** [comment]
Hi @prafull01 - thanks much! I reviewed the PR and added a few non-critical comments. Looks great.

**Comment by mprimeaux** [comment]
Hi @prafull01. Thanks again for your help.

I don’t see the new image in the container registry; [here](https://console.cloud.google.com/gcr/images/cockroachlabs-helm-charts/GLOBAL/cockroach-self-signer-cert).  The `1.4` tag is still the latest.

I think it’s because the [last build job didn’t execute](https://github.com/cockroachdb/helm-charts/actions/runs/6181618910) due to a change in tag not being detected. 

Thoughts?
